### PR TITLE
static-server mass update

### LINKED ISSUE #51: Streamline StaticWebServer
- [x] Uniform sending of all content types
  - [x] Use a `Map` from extensions to content types
  - [x] Use `application/octet-stream` default
  - [x] Always send `HdrContentLength` and `HdrContentEncoding`
- [x] Avoid `String`
- [x] Use `OverridedStrings` extension if need `ByteString` constants. `<>` is concatenation (from `Monoid` instances)
- [ ] Explicitly check for file existence to return `NotFound`. If file read fails after that and throws an exception it is caught upstream in `HTTP.Server` and results in `InternalServerError` which is more precise
- if still need to catch exceptions:
  - [x] Avoid `try` . Use `catch` or similar instead. 
  - [x] Catch the specific extension and not `SomeException`
- [x] Use `MethodNotAllowed` error code instead of `BadRequest`
- [x] Listen on `0.0.0.0` instead of `localhost` (override `srvHost`). It is more universal (e.g. works for VMs)
- [x] Use `err_response` for all errors. There is no need for response bodies. It proves too ugly, use your own `err_response` function with `reason` to synthesize the body text.
- [ ] `Text.HTML` and `Codec.Binary` go away 

There is no need for special treatment of content types. Use the same code for everything.

`Request` and `Response` seem to support `Data.ByteString` via [BufferType](https://hackage.haskell.org/package/HTTP-4000.3.3/docs/Network-BufferType.html#t:BufferType) typeclass. So just use `BS.readFile` and avoid any transcoding whatsoever.

### PR DESCRIPTION
**Pull request by swamp-agr**
closes #51.

### CODE REVIEW

File: contrib/static-web-server/StaticWebServer.hs [hunk 1]
```diff
@@ -17,41 +17,24 @@ main = serverWith defaultConfig { srvHost = "0.0.0.0", srvLog = stdLogger, srvPo
...
 
-    _ -> return $ sendHTML MethodNotAllowed $ toHtml "I don't understand"
+    _ -> return $ sendText "" MethodNotAllowed "I don't understand"
 
-sendText       :: StatusCode -> String -> Response String
-sendText s v    = insertHeader HdrContentLength (show (length txt))
+sendText e s v    = insertHeader HdrContentType (chooseCType e)
+                $ insertHeader HdrContentLength (show (length txt))
                 $ insertHeader HdrContentEncoding "UTF-8"
                 $ insertHeader HdrContentEncoding "text/plain"
```
Comment (nponeccop) [inline contrib/static-web-server/StaticWebServer.hs:29]: This is a bug. Just remove the line with "text/plain"

File: contrib/static-web-server/StaticWebServer.hs [hunk 2]
```diff
@@ -15,13 +16,7 @@ main = serverWith defaultConfig { srvHost = "0.0.0.0", srvLog = stdLogger, srvPo
...
       let ext = takeExtension (url_path url)
       putStrLn $ url_path url
-      mb_txt <- try (readFile $ url_path url)
-      case mb_txt of
-        Right a -> return $ sendText ext OK a
-        Left e -> return $ sendText ".html" NotFound "Not found"
-
-                 where _hack :: SomeException
-                       _hack = e   -- to specify the type
+      returnFileContent ext url `catch` (\(_ :: IOException) -> return $ sendText ".html" NotFound "Not Found")
```
Comment (nponeccop) [inline contrib/static-web-server/StaticWebServer.hs]: Either use 
- [System.IO.Error](http://hackage.haskell.org/package/base-4.8.2.0/docs/System-IO-Error.html) to detect "not found":

`f = catchIOError g (\e -> if IO.isEOFError e then return [] else ioError e)`
- Or `fileExists` from [System.Directory](http://hackage.haskell.org/package/directory-1.2.5.1/docs/System-Directory.html)

File: contrib/static-web-server/StaticWebServer.hs [hunk 3]
```diff
@@ -1,63 +1,42 @@
...
+               , (".html", "text/html")
+               ]
 
-extend url = case take 6 url of
-  "static" -> "../../" ++ url
-  _        -> "../../sample/" ++ url
+returnFileContent :: BS.ByteString -> URL -> IO (Response BS.ByteString)
+returnFileContent e a = do
+  b <- BS.readFile $ url_path a
+  return $ sendText e OK b
```
Comment (nponeccop) [inline contrib/static-web-server/StaticWebServer.hs:42]: This is just `sendText e OK <$>  BS.readFile $ url_path a`

File: contrib/static-web-server/StaticWebServer.hs [hunk 4]
```diff
@@ -1,63 +1,42 @@
...
-sendText s v    = insertHeader HdrContentLength (show (length txt))
+      returnFileContent (BS.pack ext) url `catch` (\(_ :: IOException) -> return $ err_response NotFound)
+
+    _ -> return $ err_response MethodNotAllowed
+
+sendText :: BS.ByteString -> StatusCode -> BS.ByteString -> Response BS.ByteString
+sendText e s v    = insertHeader HdrContentType (chooseCType e)
+                $ insertHeader HdrContentLength (show (BS.length v))
                 $ insertHeader HdrContentEncoding "UTF-8"
                 $ insertHeader HdrContentEncoding "text/plain"
```
Comment (nponeccop) [inline contrib/static-web-server/StaticWebServer.hs:29]: Remove the "text/plain" line

File: contrib/static-web-server/StaticWebServer.hs [hunk 5]
```diff
@@ -1,63 +1,42 @@
+{-# LANGUAGE ScopedTypeVariables #-}
+{-# LANGUAGE OverloadedStrings #-}
 import Network.HTTP.Server
 import Network.HTTP.Server.Logger
-import Network.HTTP.Server.HtmlForm as Form
 import Network.URL as URL
-import Text.XHtml
 import Codec.Binary.UTF8.String
```
Comment (nponeccop) [inline contrib/static-web-server/StaticWebServer.hs:6]: Do you still need the `Codec`?

File: contrib/static-web-server/StaticWebServer.hs [hunk 6]
```diff
@@ -1,63 +1,42 @@
...
+                $ insertHeader HdrContentLength (show (BS.length v))
                 $ insertHeader HdrContentEncoding "UTF-8"
                 $ insertHeader HdrContentEncoding "text/plain"
-                $ (respond s :: Response String) { rspBody = txt }
-  where txt       = encodeString v
-
-sendHTML       :: StatusCode -> Html -> Response String
-sendHTML s v    = insertHeader HdrContentType "text/html"
-                $ sendText s (renderHtml v)
+                $ (respond s :: Response BS.ByteString) { rspBody = v }
```
Comment (nponeccop) [inline contrib/static-web-server/StaticWebServer.hs:30]: Do you really need the signature here?
